#!/bin/bash

## xkfetch by tb01110100
## a general-purpose xkcd script
## depends on feh and curl
## this stuff below does stuff, or something

if [[ ! -e /usr/bin/feh ]]; then echo "this script requires feh" >&2; exit 1; fi
if [[ ! -e /usr/bin/curl ]]; then echo "this script requires curl" >&2; exit 1; fi
[[ -d ~/xkfetch ]] || mkdir ~/xkfetch

doc() {
  echo
  echo "xkfetch 0.6.1"
  echo "written by tb01110100"
  echo
  echo "usage: xkfetch [options...]"
  echo
  echo "  -t		fetch and display today's xkcd and titletext"
  echo "  -n <number>	fetch a specific xkcd and display titletext"
  echo "  -r		fetch a random xkcd"
  echo "  -m <number>	fetch a random xkcd every <number> minutes."
  echo "  -d		disable titletext printing"
  echo "  -s		save a fetched xkcd. xkcds are saved to ~/xkfetch"
  echo "  -h		display this message"
  echo
}

setvars(){
  data=$(curl -s http://xkcd.com/$xkcdnum/ | grep "imgs.xkcd.com/comics" | head -n 1)
  linkpart=$(echo $data | awk '{ print $2 }')
  xkcdurl=${linkpart:5:-1}
  xkcdtitle1=${xkcdurl:28:-4}
  titlepart=$(curl -s http://xkcd.com/$xkcdnum/ | grep "id=\"ctitle\"")
  xkcdtitle2=${titlepart:17:-6}
  titletext=$(echo ${data:$(( ${#xkcdurl} + 19 )):-$(( ${#xkcdtitle1} + 11 ))} | sed 's/&#39;/'\''/g')
}

fetch() {
  setvars
  if [[ -z $(ls ~/xkfetch | grep "$xkcdnum-") ]]; then
    curl -s -o ~/xkfetch/"$xkcdnum-$xkcdtitle1".png $xkcdurl
    echo "xkcd #$xkcdnum - $xkcdtitle2"
    [[ $title != "1" ]] && echo "$titletext"
    feh ~/xkfetch/"$xkcdnum-$xkcdtitle1".png &
    sleep 2
    [[ $save != "1" ]] && rm ~/xkfetch/"$xkcdnum-$xkcdtitle1".png
  else
    echo "this xkcd has already been saved"
    echo "xkcd #$xkcdnum - $xkcdtitle2"
    [[ $title != "1" ]] && echo "$titletext"
    feh ~/xkfetch/"$xkcdnum-$xkcdtitle1".png &
  fi
}

today() {
  numpart=$(curl -s http://xkcd.com/ | grep Permanent)
  xkcdnum=${numpart:46:-7}
  fetch
}

random() {
  numpart=$(curl -s http://xkcd.com/ | grep Permanent)
  todaynum=${numpart:46:-7}
  xkcdnum=$(shuf -i 0-$todaynum -n 1)
  fetch
}

randomtimed() {
  while :
  do
    random
    sleep $(( $minutes * 60 ))
    kill $!
    echo
  done
}

while getopts ":tn:rm:dsh" opt; do
  case $opt in
    t)
      today=1
      ;;
    n)
      xkcdnum=$OPTARG
      ;;
    r)
      random=1
      ;;
    m)
      minutes=$OPTARG
      ;;
    d)
      title=1
      ;;
    s)
      save=1
      ;;
    h)
      help=1
      ;;
    \?)
      echo "invalid option: -$OPTARG" >&2; exit 1
      ;;
    :)
      echo "option -$OPTARG requires an argument" >&2; exit 1
      ;;
  esac
done

if [[ $help = "1" ]]; then doc; exit; fi
if [[ $today = "1" ]]; then today; exit; fi
if [[ $random = "1" ]]; then random; exit; fi
if [[ -n $minutes ]]; then randomtimed; exit; fi
if [[ -n $xkcdnum ]]; then fetch; exit; fi

doc
